version: '3.7'

services:
    redis:
        container_name: redis
        image: redis:5.0
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - teastream-backend

volumes:
    redis_data:

networks:
    teastream-backend:
